/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { ReentrancyGuard } from "./ReentrancyGuard";
export type { VBitHeroes } from "./VBitHeroes";
export type { ITokenLocker } from "./ITokenLocker";
export type { VBitHeroesLocker } from "./VBitHeroesLocker";

export { Ownable__factory } from "./factories/Ownable__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { ReentrancyGuard__factory } from "./factories/ReentrancyGuard__factory";
export { VBitHeroes__factory } from "./factories/VBitHeroes__factory";
export { ITokenLocker__factory } from "./factories/ITokenLocker__factory";
export { VBitHeroesLocker__factory } from "./factories/VBitHeroesLocker__factory";
